internal.py, optimize.py, rotate.py, tools/check-convergence-qc.py
This is a start to add Python 3 support.
=> Python3 compatibility 

.travis.yml, devtools/conda-recipe/build.sh, devtools/conda-recipe/meta.yaml, devtools/travis-ci/install.sh, geometric/tests/test_import.py
This PR sets up travis by adding a `.travis.yml` file and `conda-recipe` and a simple import nosetest.
=> Set up travis

geometric/engine.py, geometric/internal.py, geometric/molecule.py, geometric/nifty.py, geometric/optimize.py, geometric/rotate.py
molecule.py and nifty.py files from ForceBalance are added (not modified from FB versions). These provide file / coordinate manipulation, as well as process control utilities.
=> Lighten dependencies (remove dependencies on ForceBalance and SciPy).

geometric/run_json.py, geometric/tests/test_run_json.py
This PR addresses #26 
The constraints dictionary is tured into a string, then passed to the `geometric.optimize.ParseConstraints()` function. In this way we avoid rewriting the above function.
=> update constraints format in JSON input

geometric/_version.py
As noted, fixes the in-place versioneer `__version__` tags.
=> Version: Fixes inplace versioneer builds

geometric/molecule.py
Porting a few fixes from ForceBalance molecule.
=> Port molecule

examples/water6_molpro/rhf/command.sh, geometric/engine.py, geometric/optimize.py
Reverts leeping/geomeTRIC#28
I realized that `exe` is not implemented for the other engines yet.  Reverting the PR until I've done that.
=> Revert "Cleanup and new option for Molpro engine"

examples/pentacene/penta2.tcin, geometric/internal.py, geometric/molecule.py, geometric/nifty.py, geometric/optimize.py, geometric/rotate.py, setup.cfg
This PR follows up on @loriab 's changes; made some more changes to retain Python 2.7 compatibility.  I still don't know what the regex errors are.
=> Remove all calls to np.matrix

geometric/internal.py, geometric/optimize.py
Allows the capturing of errors when calling from API.
=> Raises exceptions instead of exiting

geometric/optimize.py, geometric/tests/test_customengine.py
Thanks for implementing the excellent geometry optimization library. It would be helpful if the optimize function can be used with a customized engine other than the predefined programs.
Added an entry "customengine" in optimize function to support this.
=> Add custom engine

.travis.yml, devtools/conda-envs/openmm.yaml, devtools/conda-envs/psi.yaml, devtools/scripts/create_conda_env.py, devtools/travis-ci/before_install.sh, geometric/engine.py, geometric/optimize.py, geometric/run_json.py, geometric/tests/addons.py, geometric/tests/test_openmm.py, geometric/tests/test_run_json.py
1) Added a feature allowing energies and gradients to be computed using OpenMM, given a PDB file containing the topology of the system, and either a state.xml or system.xml file.  
2) Added unit test for OpenMM engine that contains a breakdown and rebuild of the internal coordinate system.
3) Updated .travis.yml, create_conda_env.py and before_install.sh from cookiecutter.
=> Openmm engine

geometric/optimize.py
This PR makes custom convergence criteria available via the command line interface.
Because (1) there are many possible convergence criteria to choose from and (2) I don't want to grow the number of command line options too much, the CLI is defined in the following way:
- The user specifies `--converge` followed by pairs of values, such as `energy 3e-6 grms 1e-3`.
- The first word in the pair is converted to a keyword argument that is passed to the `OptParams` constructor by prepending `convergence_`, i.e. `energy -> convergence_energy`.
- Once the convergence parameter is set in `OptParams`, the optimization method will use it.
It is also possible to set the two special "Molpro" convergence criteria by passing `molpro_gmax` and `molpro_dmax` as options to `--converge`.  I changed the …
=> Custom convergence criteria

geometric/engine.py
This improves the functionality of the TeraChem engine by allowing "fragment-style" guesses to be passed to TeraChem.  An example on a project molecule will be added after the paper is published.
To use the new feature, use the following line in the TeraChem input file:
```guess          frag frag.txt```
The contents of `frag.txt` (the file name can be changed) specifies the fragments and their charges/spins as described by the TeraChem manual:
```2
17 -2 1 a
8 0 2 a
```
This means there are 17 atoms in the first fragment with a charge of -2, spin multiplicity 1, and the unpaired electrons are spin-up (none in the first molecule).
When fragment-style guesses are used, they will be used throughout the optimization (i.e. step n+1 will no longer use the step n converged result as the guess). …
=> TeraChem fragment guess

geometric/optimize.py, geometric/tests/test_errors.py, geometric/tests/test_run_json.py
=> move sys.exit() to main() function

geometric/engine.py
QCElemental has a new serialization scheme that will need a fix from the following line. This change is fully backwards compatible.
=> QCElemental Updates

.codecov.yml, .travis.yml, devtools/conda-envs/psi.yaml, geometric/optimize.py, geometric/run_json.py, geometric/tests/test_batch_opt.py, geometric/tests/test_errors.py, geometric/tests/test_openmm.py, geometric/tests/test_run_json.py
There are no tests specific to transition state optimization yet.  This makes sure all the existing tests pass, since they have been broken for a while.
=> Transition state optimization: Make sure all tests pass

devtools/travis-ci/before_install.sh
Looks like you've already fixed this in forcebalance!
=> Update miniconda URL from continuum.io to anaconda.com

geometric/molecule.py, geometric/nifty.py
This PR ports some changes to molecule.py and nifty.py from ForceBalance. Both files are fairly stable and heavily used by both packages.
=> Sync molecule.py and nifty.py with ForceBalance

.coveragerc, geometric/neb.py, geometric/tests/test_neb.py
Unused functions in neb.py were removed. neb_test.py was updated to increase the test coverage.
=> Neb test updated

geometric/params.py
=> Interpolate parameter bug fixed

geometric/params.py, geometric/tests/test_neb.py
NEB can now be performed with the work queue.
=> Work queue for NEB. Test was added as well.
