leeping/geomeTRIC

geometric/engine.py
On Ubuntu 16.04, the Python subprocess.call with the `&>` symbol will be parsed as `run in background`. Swtiching it to `2>&1` will solve the problem.
=>  fix &> symbol in subprocess call

.travis.yml, geometric/molecule.py
For some reason, the line `from builtins import input` was missing at the top, leading to errors when users were asked to enter strings in Python 2.7. This should fix the issue.
=> Add builtins to molecule.py

.travis.yml, devtools/conda-envs/psi.yaml, devtools/conda-envs/rdkit.yaml, devtools/travis-ci/before_install.sh, geometric/engine.py, geometric/optimize.py, geometric/run_json.py, geometric/tests/addons.py, geometric/tests/test_import.py, geometric/tests/test_qcengine.py, geometric/tests/test_run_json.py
This PR accomplishes several tasks:
- Fixes a QCEngine JSON bug.
- Tweaks the folder structure to use PyTest fixtures that do not conflict with standard PyTest machinery.
- Adds a Psi4 QCEngine test.
- Reworks some of the Travis/conda mechanics to reduce conda installs and allow for both RDkit + Psi4 testing.
This will not pass until a new QCEngine version is minted which will happen soon.
=> JSON Tweaks

geometric/optimize.py, geometric/run_json.py
This PR is created for improving the `constraints` specification in json format.
The parsing of constraints were previously done by openning a file then read line by line. Therefore the input json file has to specify a `constraints`: `filename` to allow this. This is not preferred.
To allow specifying the constraints directly in the input json file, a small tweak has to be done in `geometric.optimize.ParseConstraints()` function, which now takes a string, equal to the content of the constraints file, as input parameter. This allow us to put the constraints string in the json input file and parse it in `geometric.optimize.ParseConstraints()`.
=> improve the constraits spec in json input

geometric/optimize.py, geometric/run_json.py, geometric/tests/test_run_json.py
This PR accomplishes two small goals:
- Moves the initial molecule out of the QC JSON specification so that we can have canonical `initial_molecule` and `final_molecule` fields.
- Avoids writing `energy.txt` during API calls.
Please squash the PR upon merging.
=> JSON API tweaks

setup.py
Previously the `geometric/tests` folder was not supplied to `setup.py` packages meaning in place testing always failed. The PR makes additional tweaks to test installations and classifiers.
=> Updates setup.py

geometric/internal.py, geometric/nifty.py, geometric/optimize.py, geometric/rotate.py
Running a single optimization generates about a thousand warnings of `PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.`
* This at least fixes the ones my tests hit -- I'm nervous about adjusting uncovered code. 
* I used `@` for matrix multiply of `np.array`. If you're planning to support <3.5 for much longer, should switch to `np.dot()`
* I've also seen the below warnings, but I'm not about to second-guess someone else's regexes.
```
/home/psilocaluser/gits/geomeTRIC/geometric/nifty.py:249: DeprecationWarning: invalid escape sequence \[
return len(re.sub("\x1b\[[0-9;]*m","",l)) …
```
=> suppress np.matrix and docstring escape char warnings

geometric/molecule.py, geometric/nifty.py
This PR allow geomeTRIC to be a bit more friendly in logging by encapsulating specific geomeTRIC logic to scooped loggers. This no longer clears global loggers and allows canonical logger propagation.
=> Prevent logger overwriting all logging settings

geometric/engine.py, geometric/optimize.py, geometric/run_json.py, geometric/tests/test_qcengine.py, geometric/tests/test_run_json.py
Allows the `run_json` command to fill in what it can of trajectory data if an individual computation fails.  Example:
```
ret = geometric.run_json.geometric_run_json(in_json_dict)
assert ret["success"] == False
assert "run_json error" in ret["error_message"]
assert ret["trajectory"][-1]["success"] == False
```
This will help JSON users downstream to track errors better.
Also consolidates JSON input generators to single functions or blobs to reduce duplication.
=> Error Handling

.travis.yml, devtools/conda-envs/latest.yaml, devtools/conda-envs/rdkit.yaml, geometric/run_json.py, geometric/tests/test_run_json.py
This PR does the following:
- Moves JSON specification to zero-index (will impact torsion drive)
- Pins QCEngine version via GitHub, so we can look at the latest release and the latest version
- Adds a new constraint specification that looks like:
```
constraint_dict = {
'freeze': [{
"type": ("xyz", [0, 1, 2])
}],
'set': [{
"type": ("angle", [1, 0, 4]),
"value": 110.0
}],
'scan': [{
"type": ("distance", [1, 0]),
"start": 1.0,
"stop": 1.2,
"steps": 3
}, {
"type": ('dihedral', [0, 4, 5, 6]),
"start": 110.0,
"stop": 150.0,
"steps": 3
}]
}
```
=> JSON interface update

.travis.yml, geometric/engine.py
Tiny change so that full traceback is printed when a QCEngine calculation is not executed correctly.
=> print full traceback when success if false

.travis.yml, devtools/conda-envs/latest.yaml, devtools/conda-envs/psi.yaml, devtools/conda-envs/rdkit.yaml, geometric/engine.py, geometric/run_json.py, geometric/tests/test_run_json.py
The distance constraints were previously not correctly accepting Bohr like the rest of the schema leading to errors. This is now corrected.
This PR also unpins the QCEngine version as that code has stabilized.
If possible, it would be good to get this in make a patch version soon so that Fractal can correctly optimize these.
=> Schema: Distance constraints

devtools/conda-envs/latest.yaml, devtools/conda-envs/psi.yaml, devtools/conda-envs/rdkit.yaml, geometric/PDB.py, geometric/engine.py, geometric/internal.py, geometric/molecule.py, geometric/nifty.py, geometric/optimize.py, geometric/rotate.py, geometric/run_json.py, geometric/tests/addons.py, geometric/tests/test_run_json.py
We are planning to change the QCEngine return to an object representation of the QCSchema by default rather than a straight dictionary. This change will force a dictionary return so that this transition will not effect geomeTRIC.
=> QCEngine: compute return update

MANIFEST.in
The data folder was not correctly installed when using `setup.py install` or `Conda-build` causing installed tests to fail.
=> Manifest: Now includes the new data folder

geometric/internal.py, geometric/tests/test_diff.py, geometric/tests/test_hessian.py, geometric/tests/test_openmm.py, geometric/tests/test_rotate.py
The `repr_diff()` function in `PrimitiveInternalCoordinates` and `DelocalizedInternalCoordinates` were not mutually compatible, this should fix it.
=> Fix repr_diff() function

devtools/conda-envs/psi.yaml, geometric/engine.py, geometric/errors.py, geometric/optimize.py, geometric/tests/test_errors.py, geometric/tests/test_run_json.py
This PR improves behavior of handing errors from `Engine` objects.
- When a QM gradient calculation fails:
previous behavior: geomeTRIC will exit with error code 1, printing traceback of source code.
new behavior: geomeTRIC will exit with error code 51, raising EngineError and printing trackback.
- When the geomeTRIC optimization failed to converge:
previous behavior: geomeTRIC print a warning and exit normally with code 0.
new behavior: geomeTRIC raises an `ConvergeFailedError` and exit with code 50.
The new error handling feature will allow other programs interfacing with geomeTRIC either by command line or by python modules be able to get insights about reason of failing, and take corresponding actions.
=> implement error handling for engines

geometric/run_json.py, geometric/tests/test_run_json.py
This PR addresses the bug discussed in #85
=> fix bug in run_json for constraint type "xyz"

geometric/optimize.py
This PR will resolve #9 .
Very small or negative Hessian eigenvalues often occur together with poor convergence behavior in energy minimization.  The `--reset` command line option was added as an option to reset the Hessian to the guess whenever any eigenvalue drops below the small-eigenvalue threshold `--epsilon` (default 1e-5).  
I hesitated to make this the default behavior for a long time because there are cases where very small eigenvalues do help to reach convergence, but now I am fairly convinced that they are few and far between.  After this PR, resetting the Hessian will be the default behavior.  The `--reset` option is still there, but it no longer does anything and will soon be removed.  The `--no_reset` option is added for disabling the Hessian-resetting behavior if needed. …
=> Make --reset the default behavior

LICENSE, geometric/molecule.py
This PR silences some irrelevant warnings in `molecule.py` and changes the license to the BSD 3-clause license.
=> Silence warnings in molecule.py and change license to BSD

geometric/engine.py
The default schema now uses a `None` value for `connectivity` rather than an empty list to denote this value has not been set. This causes an issue in several round trip values within QCFractal.
It would be great to push out a patch release if you do not mind.
=> QCEngine: Connectivity allows new None default value to pass through

geometric/engine.py, geometric/molecule.py, geometric/optimize.py
Enables hybrid QM/MM optimizations using TeraChem/OpenMM (only QM atoms are optimized).
The QM-MM interface is designed on the following ideas:
1) We are only optimizing the QM portion of the system (until we implement fast inversion of G matrices and Hessians)
2) The geomeTRIC optimizer only "sees" the part of the molecule being optimized.
3) The TeraChem engine writes .rst7 files instead of .xyz files by inserting the optimization coordinates into the correct atomic indices.
=> QM/MM optimizations in TeraChem (QM atoms only)

geometric/engine.py, geometric/internal.py, geometric/optimize.py, geometric/params.py, geometric/step.py
This fixes a few issues:
- In the stepping algorithm, `Eig[1]` was a mistake and is now fixed to `Eig[0]`.  No performance impact was found on test jobs.
- In the relatively rare failure mode when SVD fails for a given Hessian matrix, the matrix is saved for debugging purposes.
- `printRotations` was previously working only with DelocalizedInternalCoordinates, it should now work with all coordinate systems, even those without rotators.
Thanks to @shiozaki for catching these.
Additionally:
- OpenMM force field XML files can be used as input files even if they aren't in the current folder (OpenMM will look for them in its data folder).
- Added TrpCage examples.
=> Fix Eig[1] problem, HT diagnostic

geometric/data/ethanol.pdb, geometric/data/ethanol.xml, geometric/engine.py, geometric/tests/test_openmm.py
Added functionality to allow virtual sites in geomeTRIC optimisations when using OpenMM.
This works by updating the OpenMM system to be built with a modeller which accepts the virtual sites. The virtual sites (if present) are counted and applied in OpenMM.calc_new() in engine.py for the energy/gradient calculations.
Added tests for ethanol with two virtual sites. GeomeTRIC, calculates and confirms the energy and gradient.
=> V sites modeller

geometric/molecule.py
An increment of 15 degrees was hard coded in this method to rotate about a bond in the method `rotate_check_clash`. Changed this to accept any increment using an additional argument called `increment` with a default value of 15 degrees.
=> Adding increment argument to rotate_check_clash method in molecule.py

.github/workflows/codeql-analysis.yml, .github/workflows/test-conda.yml, .github/workflows/test-pip.yml, docs/source/citation.rst, docs/source/install.rst, geometric/tests/addons.py, geometric/tests/test_customengine.py, geometric/tests/test_gaussian.py, geometric/tests/test_hessian.py, geometric/tests/test_prepare.py, geometric/tests/test_run_json.py
Testing suite executed in GitHub Actions, replacing the deprecated travis-CI runners.
The following actions have been implemented:
- tests & coverage with pip-based environment: python 3.6 to 3.10, all versions in parallel
- tests & coverage with a Conda environment: Python 3.8 only. This is a longer running one, where calculators exist as well.
- CodeQL: github's code analysis - this is good in general to be executed on the main branch from time to time, will highlight some issues if they arise with the codebase
Small changes were made in the tests to account for cases where engines are not installed and the number of steps required to converge within has been loosened in a test where it was failing. The latter may require attention beyond the scope of this PR.
=> GitHub actions

geometric/tests/test_ase_engine.py
Since it is an optional add-on and it's not listed in the installation requirements.
=> Do not import ASE stuff at the top

geometric/internal.py
algorithm for constraint satisfaction may not applicable for every internal coordinates scheme, but for compatible purpose it maybe better to return a `None` if it is not applicable.
=> [fix] add `conmethod` for `InternalCoordinates`

geometric/neb.py, geometric/qcf_neb.py, geometric/tests/test_neb.py, setup.py
`neb.CalcInternalStep` calculates eigenvalues of the Hessian to take the very first step of NEB through `qcf_neb.prepare`. When an NEB chain consists of many images of big molecules, the eigenvalue calculation requires significant amount of CPUs and memory. This can be a problem when a couple of hundred NEB services are running concurrently in a QCFractal server. This is solved by passing the first step procedure to `qcf_neb.nextchain` as it is already handled by workers. 
Scipy was added into `setup.py` as well.
=> qcf_neb.nextchain handles the first NEB step instead of qcf_neb.prepare

geometric/optimize.py, geometric/qcf_neb.py
Following bugs were fixed for IRC:
1) `evaulate_OPT_step` function was missing a few parameters.
2) When the forward direction IRC switched to optimization mode, it completed the calculation without performing the reverse IRC.
3) The verbose option was added.
One NEB modification:
1) `hessian_reset` option for QCF/NEB was deleted.
=> IRC bug fix and NEB update
